version: '3.9'

services:
  nextjs:
    build: ./nextjs-docker
    restart: always
    ports:
      - 3000:3000
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
      # or set shared memory limit when deploy via swarm stack
      #volumes:
      #  - type: tmpfs^
      #    target: /dev/shm
      #    tmpfs:
      #      size: 134217728 # 128*2^20 bytes = 128Mb
      # volumes:
    # - ./var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: azerty
      POSTGRES_DB: true_crime
      POSTGRES_USER: user

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "azerty"
      PGADMIN_SERVER_JSON_FILE: "/pgadmin4/servers.json"
    volumes:
      - ./etc/pg/servers.json:/pgadmin4/servers.json
    depends_on:
      - db

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3001:3000"

  prometheus:
    image: prom/prometheus
      # volumes:
    # - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    ports:
      - "9090:9090"